
package com.sun.mdm.index.webservice;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.11.fuse-710022-redhat-00001
 * 2019-04-24T22:51:15.390-05:00
 * Generated source version: 3.1.11.fuse-710022-redhat-00001
 */

@WebFault(name = "PageException", targetNamespace = "http://webservice.index.mdm.sun.com/")
public class PageException_Exception extends Exception {
    
    private com.sun.mdm.index.webservice.PageException pageException;

    public PageException_Exception() {
        super();
    }
    
    public PageException_Exception(String message) {
        super(message);
    }
    
    public PageException_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public PageException_Exception(String message, com.sun.mdm.index.webservice.PageException pageException) {
        super(message);
        this.pageException = pageException;
    }

    public PageException_Exception(String message, com.sun.mdm.index.webservice.PageException pageException, Throwable cause) {
        super(message, cause);
        this.pageException = pageException;
    }

    public com.sun.mdm.index.webservice.PageException getFaultInfo() {
        return this.pageException;
    }
}
